language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: d6d993d1-f231-4803-ac84-a7cbfbc40b19
  app: asd-dash
  on:
    repo: uva-cs3240-s20/project-102-asdfghjkl
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
