language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
- python manage.py makemigrations
- python manage.py migrate
deploy:
  provider: heroku
  api_key:
    secure: Kl6oA6l7GzWIKTehvFY25AWuZ8e3WJaaC8Sgv9JuyNkWuSpXAv4R6nHbVi5KmWu+e3fhIdIlKWk+q+LXLJyn3dt0u41SlBUom3BkJZrKCBx1v1hM1kjSrQZA/lo7RyAubMM2ZSgvy/n+fPzWH2rs9BhdnMykT9KLlSQlIAhcSJekN6sS1+C0cHPpuipZTXv8bm2NRlKLR7Z3cRAM+lgGaoWTBHR3KdCfjMcS/EOCFbsRo/HyuiLbTq23vvolFh/xMfg42e/5YnPJd0LBj9rn7TSsNK0nlETG2gPx22sKi4xzdIP/OKe3MPItKCDfLMaozW/aMji+d7vEq0v6yCeddzYpbcCkT9hFSjFFVm/UqMH1BZXuMJ5bgLPXbsBlWHgUNw5kedet4K8G75yLeiDL07lUqKZbquPNvbTHE5/IFfNhcYs2EDYMeVujdCo1kKifSnML+MM75fu5bDZL+mZLpeCHNk62oAyAEX6OMHjQEvURt206bRCBf2+o8IC9urQIXouxqD4jGftG6leOULgGXuG6M6zLazeBZ0X28ENz+n4h+j2g3Ur8TOaJR4h20PPUnmgSi/zmeC4U1pTudUEKMikdOiu5cCz0EHepHkx4g0fW1TP0EQwI0aO7n9yA8E46N6eT4YwMjp5542w7tgRNnGLcWZBQ6InaELkJBNOxwCI=
  app: asd-dash
  on:
    repo: uva-cs3240-s20/project-102-asdfghjkl
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres