language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: f6zPpHDtXwmLIFgQEurUj7qd1hvfH4LV+bSN7n+oJo6mkS42FCGhYwdeeswOPaz8LLpKuSD/PBIJMdP3oKQhv22/cTNQJlMym3YigFsmk3a5WQhxv29hlgu7vof8aWS2Eux8zomfAdapAZmXBGIcEWtFk1BnM0qXPJoH4mff3EJ+EtEQzr6UQpvDtThsI4+gsJsVxQSg0JU0GjTuCewWV1qWIEv+zvFvQar5NHhnZQQo7fihklCX08xqfA7pHmfPLgWZyGl+vckhfYOk/P9SNZsN7sdle1voJRS6aZnEflQORqdDhQo0J86WUp2DlwHC81O5XnWRvyaQjOmHhR8FgSZ7Au6b29q6BmLVZIff2LRiKK6GThbi7gREeICZFwrn15kDCzLYSgFMJXfmrBCrmB2ArFoulEHYuDp0TgMIBjnsxBOAyMCJBpOSRyxu+ExpGAGdpAWLjU7M9rdntt8I5gL8HkwfVzMkqv7gph0atM4XiStQqoBzXbOZIsqfCP+HSgV2WzX/EmP1QZL9/O3bxGRaFDra3TvLLmEjPkg5j8D7gI7raqUhzbpe15VZg1qOZ19A86hloF1DiviPEtNDem+k9pDV/xXp/jphimS0VBkvArVd94T5RfKwpQgHha+dQA71c/iiVjo3zOill5NbAyYgW2WSXFjd2RrR6e0M69Q=
  app: asd-dash
  on:
    repo: uva-cs3240-s20/project-102-asdfghjkl
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
